"""
Dummy restaurant data for testing
"""

restaurants = [
    {
        "id": "rest_001",
        "name": "築地壽司",
        "cuisine": "日式",
        "distance_km": 0.8,
        "tags": ["經典", "壽司", "新鮮"],
        "rating": 4.5,
        "address": "台北市中山區中山北路二段123號",
    },
    {
        "id": "rest_002",
        "name": "創意日料",
        "cuisine": "日式",
        "distance_km": 1.2,
        "tags": ["新口味", "創意", "精緻"],
        "rating": 4.2,
        "address": "台北市信義區松高路456號",
    },
    {
        "id": "rest_003",
        "name": "老北京炸醬麵",
        "cuisine": "中式",
        "distance_km": 0.5,
        "tags": ["經典", "麵食", "傳統"],
        "rating": 4.0,
        "address": "台北市大安區復興南路789號",
    },
    {
        "id": "rest_004",
        "name": "川味新食堂",
        "cuisine": "中式",
        "distance_km": 2.1,
        "tags": ["新口味", "川菜", "辛辣"],
        "rating": 4.3,
        "address": "台北市松山區南京東路321號",
    },
    {
        "id": "rest_005",
        "name": "義大利麵屋",
        "cuisine": "義式",
        "distance_km": 1.5,
        "tags": ["經典", "義大利麵", "起司"],
        "rating": 4.1,
        "address": "台北市中正區忠孝西路654號",
    },
    {
        "id": "rest_006",
        "name": "創新義法料理",
        "cuisine": "義式",
        "distance_km": 3.0,
        "tags": ["新口味", "融合", "高檔"],
        "rating": 4.6,
        "address": "台北市大同區重慶北路987號",
    },
    {
        "id": "rest_007",
        "name": "韓式燒烤",
        "cuisine": "韓式",
        "distance_km": 1.8,
        "tags": ["經典", "燒烤", "韓國菜"],
        "rating": 4.2,
        "address": "台北市萬華區西門町147號",
    },
    {
        "id": "rest_008",
        "name": "現代韓食",
        "cuisine": "韓式",
        "distance_km": 2.5,
        "tags": ["新口味", "現代", "健康"],
        "rating": 4.4,
        "address": "台北市內湖區內湖路258號",
    },
]
